version: "3"
services:
  api:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  proxy:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  visualizer:
    deploy:
      placement:
        constraints: [node.role == manager]